### ISSUE TITLE
Regarding the model proposed in the paper

### ISSUE THREAD

**Issue by charmm09** [ashraf-rashid/BicephNet-for-Alzheimers-Disease-Classification#1]
Hello, I have recently read your paper "Biceph-Net: A robust and lightweight framework for the diagnosis of Alzheimer’s disease using 2D-MRI scans and deep similarity learning".I have a question I hope you can answer.Why does the model in the paper not reflect the use of KNN but the code uses KNN_Classifier?Looking forward to your reply, thanks!

**Comment by ashraf-rashid** [comment]
KNN is used for interpreting the classifications performed by the network. More discussion can be found in the model interpretability section of the paper.

**Comment by charmm09** [comment]
Okay, thanks.
